### ISSUE TITLE
disable coding on source nodes

### ISSUE THREAD

**Issue by majidlotfian** [steinwurf/kodo-basic-simulations#10]
hi everybody
how can I disable coding on source nodes?
first I commented this line on basic_source.hpp file :

void tick()
    {
        ++m_counter["source_sent"];

```
    m_encoder->encode(&m_payload[0]);**********    this line     *************

    packet p(m_payload);
    p.set_sender(node_id());
    forward_packet(p);
}
```

but my code was not run any more.
how can I disable coding on sources completely ?

**Comment by mortenvp** [comment]
You have to send the packet without encoding it. You can make your own 
small packet header that you read at the relay so that you know which 
packet it is etc.

- M
