### ISSUE TITLE
Issue of compiling UDP_Sender_Receiver

### ISSUE THREAD

**Issue by cmphuc** [steinwurf/kodo-basic-simulations#16]
I modify the source code of udp_sender.cpp and try to compile.

I use these command for compiling:

g++ \
-O2 \
-ftree-vectorize \
-std=c++0x \
-I../../src \
-I../../bundle_dependencies/boost-abe3de/1.7.0 \
-I../../bundle_dependencies/cpuid-4d8071/3.1.0/src \
-I../../bundle_dependencies/fifi-8960fd/15.0.0/src \
-I../../bundle_dependencies/platform-bccd32/1.1.0/src \
-I../../bundle_dependencies/recycle-b2469b/1.0.1/src \
-I../../bundle_dependencies/sak-1bdcea/13.0.0/src \
udp_sender.cpp \
-o udp_sender \
-Wl,-Bstatic \
-L../../kodo_build \
-lfifi \
-lcpuid \
-lsak \
-Wl,-Bdynamic

But the compiler notified the following errors. Please help me the method for compiling.

/tmp/ccEzKlj2.o: In function `boost::asio::detail::tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::task_io_service, boost::asio::detail::task_io_service_thread_info>::context>::~tss_ptr()':
udp_sender.cpp:(.text._ZN5boost4asio6detail7tss_ptrINS1_10call_stackINS1_15task_io_serviceENS1_27task_io_service_thread_infoEE7contextEED2Ev[_ZN5boost4asio6detail7tss_ptrINS1_10call_stackINS1_15task_io_serviceENS1_27task_io_service_thread_infoEE7contextEED5Ev]+0xc): undefined reference to`pthread_key_delete'
/tmp/ccEzKlj2.o: In function `boost::asio::detail::tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::strand_service::strand_impl, unsigned char>::context>::~tss_ptr()':
udp_sender.cpp:(.text._ZN5boost4asio6detail7tss_ptrINS1_10call_stackINS1_14strand_service11strand_implEhE7contextEED2Ev[_ZN5boost4asio6detail7tss_ptrINS1_10call_stackINS1_14strand_service11strand_implEhE7contextEED5Ev]+0xc): undefined reference to`pthread_key_delete'
/tmp/ccEzKlj2.o: In function `boost::asio::detail::task_io_service::shutdown_service()':
udp_sender.cpp:(.text._ZN5boost4asio6detail15task_io_service16shutdown_serviceEv[_ZN5boost4asio6detail15task_io_service16shutdown_serviceEv]+0x7c): undefined reference to`boost::system::system_category()'
/tmp/ccEzKlj2.o: In function `boost::asio::detail::task_io_service::post_deferred_completions(boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&)':
udp_sender.cpp:(.text._ZN5boost4asio6detail15task_io_service25post_deferred_completionsERNS1_8op_queueINS1_25task_io_service_operationEEE[_ZN5boost4asio6detail15task_io_service25post_deferred_completionsERNS1_8op_queueINS1_25task_io_service_operationEEE]+0x30): undefined reference to`pthread_getspecific'
......

**Comment by mortenvp** [comment]
Hi, it seems you are getting linker errors to pthread. Try adding `-pthread` to the command you use for compiling. Btw. I don't think we have a udp_sender.cpp in this project, it this something you wrote?
