### ISSUE TITLE
expanding relay_simulation example

### ISSUE THREAD

**Issue by majidlotfian** [steinwurf/kodo-basic-simulations#8]
I have expanding this example for my topology and faced with many errors
can anyone help me to solve this errors?
I have attached my code in this page : 
https://groups.google.com/forum/#!topic/steinwurf-dev/rt11D4NAz8Q

**Comment by mortenvp** [comment]
Hi @majidlotfian 
The way the simulator works is that you parse the options in the `get_options` function and create the "config_set" so you can use it in the `setup` function. 

In your case you querying the `config_set` for values you do not set in the `get_options` function. The error is telling your it cannot find values you ask for. E.g. 

```
  double error_s1_d1 = cs.get_value<double>("error_s1_d1");
```

Needs an equivalent `cs.set_value<double>("error_s1_d1", some_value)` in the `get_options` function.

**Comment by mortenvp** [comment]
I will close this issue.
